src/pages/cart/cart.html

cart.html 마크업 기본구조 작성
cart.html 마크업 기본구조 작성
cart.html 마크업 기본구조 작성

[🎨Modify]: cart.html 마크업 기본구조

---

index.html
tailwind.config.js

- index.html에 og:title 추가
- tailwind.config 파일에 colors, fontSize 추가
- index.html og 서비스 추가
- tailwind.config extend > colors와 fontSize 추가

[🎨Modify]: html에 og, tailwind.config에 색상, 폰트

---

README.md

Seungjunhwang patch 1

---

template.html

template.html 생성
html 작성하실 때 복사해서 사용하시면 됩니다.

[🔧Add]: template.html 추가

---

index.html
src/styles/tailwind.css

- meta태그 내용 작성 및 Pretendard 폰트 적용

[🎨Modify]: meta태그 내용 작성 및 Pretendard 폰트 적용

---

index.html
src/pages/cart/cart.html
template.html

template.html 수정, 파비콘 추가
template.html 수정
template.html 수정, 파비콘 추가

[🎨Modify]: template.html 수정

---

package-lock.json
package.json
postcss.config.js
src/styles/common.css
src/styles/font.css
src/styles/footer.css
src/styles/tailwind.css

- tailwind.css 공통작업을 위한 postcss-import 설치
postcss-import 설치
tailwind.css에 import해주시면 됩니다.
resolves #73

[🏛️Build]: postcss-import 패키지 설치

---

index.html
main.js

[🎨Modify] : 2번째 상품 swiper 80%완성(화살표 구현 필요)

---

index.html
src/pages/productList/index.html

[🎨Modify]: a 요소 경로 수정

---

public/components/header/header.html
src/pages/cart/index.html

- header 컴포넌트 내에 카트 경로 추가
- cart html에 include.js type=module 추가

[🎨Modify]: header에 cart 경로 추가

---

index.html
main.js

[🎨Modify] : main HTML UI 사이드바 제외하고 완성
- 시안의 swiper 기능 전혀 구현
- 사이드바를 제외한 UI 완료

[✨Feat] : swiper 기능 시안+@ 구현

---

src/components/header/header.html
src/js/include.js
src/pages/register/index.html
src/pages/register/register.js
src/styles/register.css
src/styles/tailwind.css
vite.config.js

[Modify] 회원가입 마크업 작업

---

src/pages/register/index.html
src/styles/common.css
src/styles/register.css

[🎨Modify]: 이용약관 마크업 구조 변경 및 레이아웃 수정

---

src/components/addCart/addCart.html
src/components/addCart/addCart.js
src/js/include.js
src/pages/cart/index.html
src/styles/addCart.css
src/styles/cart.css
src/styles/header.css
src/styles/tailwind.css
vite.config.js

addCart 컴포넌트 기능 추가
addCart 컴포넌트 
- open, close 기능추가
- include.js 에 추가
resolves #32

addCart 컴포넌트 open, close 기능

---

src/pages/register/index.html
src/pages/register/register.js
src/styles/register.css

- 회원가입 이용약관 마크업 수정
resolves #84

[🎨Modify]: 회원가입 마크업 완성

---

src/pages/productDetail/index.html
src/pages/productDetail/productDetail.js

- 수량 체크 시 총 금액 변경
- + - 버튼 누르면 수량 변경
- 수량 변경 시, 총 금액 변경
resolves #39

[✨Feat]: 수량 체크 시 총 금액 변경

---

index.html

- 사라졌던 main의 index 페이지 복구 및 데이터 바인딩

[🐛Fix]: main의 index페이지 복구

---

.gitignore
src/pages/login/login.js

.env 파일 추가
- pockethost 경로 환경변수에 저장

[📑Docs]: .env 파일 생성

---

index.html
src/pages/productDetail/index.html
src/pages/productDetail/productDetail.js
src/styles/detail.css

- Tab기능 구현
- Tab 버튼 클릭 시 해당 section으로 이동
- aria-selected 변경

[✨Feat]: Tab 기능 구현

---

.gitignore
src/pages/login/index.html
src/pages/login/login.js

[Feature] DB의 유저 정보와 입력 값 비교, 로그인 후 로컬스토리지에 유저 id 저장
resolves #127

[Feature] DB의 유저 정보와 입력 값 비교, 로그인 후 로컬스토리지에 유저 id 저장

---

index.html
src/pages/productList/index.html
src/pages/productList/productList.js

[🎨Modify]: productList HTML & CSS 요소 완료

---

index.html
src/pages/productList/index.html

[🎨Modify] : swiper 반응형으로 수정

---

index.html
src/pages/productDetail/accumulatePoints.js
src/pages/productDetail/index.html

[✨Feat]: 로그인 시, 적립

---

src/components/header/header.html
src/components/modal/modal.js
src/js/include.js
src/pages/login/index.html
src/pages/login/login.js
src/pages/register/index.html
src/pages/register/register.js
src/styles/header.css

- 모달창 컴포넌트로 생성
- header z-index 값 변경

[Feature/header#157] 모달창 구현
